language: php
php:
    - '7.2'

sudo: enabled

script:
    - composer install
    - bin/console doctrine:database:create --env=test
    - bin/console doctrine:schema:update --force --env=test
    - vendor/phpunit/phpunit/phpunit