# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    username_to_ignore: anonyme

services:
    user_manager:
        class: AppBundle\Manager\UserManager
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@security.password_encoder"

    AppBundle\Controller\UserController:
        arguments:
            $usernameToIgnore: "%username_to_ignore%"